### ISSUE TITLE
clarify TLS backend

### ISSUE THREAD

**Issue by 89z** [juancarlospaco/harpoon#5]
I am looking for alternative to `std/httpclient`, since is relies on OpenSSL

can you clarify what TLS is used here?

**Comment by juancarlospaco** [comment]
The repo does not contain any code for SSL at all, it is agnostic.

It is just a function that takes a Socket, similar to JS Fetch,
and it will use whatever the Socket you passed as argument has,
you can provide a custom Socket with a custom or no SSL etc.
